In [1]:
import numpy as np

In [2]:
#in 1d array we pass the list
np_1d=np.array([1,2,3,4,5])

In [4]:
print(np_1d)

[1 2 3 4 5]


In [5]:
np_1d.size

5

In [6]:
np_1d.ndim

1

In [7]:
np_1d.shape

(5,)

### 2d-array:

In [9]:
#in 2d array we pass the list of lists:
np_2d=np.array([[2,3,4,5],[5,6,7,8]])

In [10]:
print(np_2d)

[[2 3 4 5]
 [5 6 7 8]]


In [11]:
#to know shape of array:(rows,columns)
np_2d.shape

(2, 4)

In [12]:
#to know the dimension:1d,2d,3d
np_2d.ndim

2

In [13]:
#to know the no of elements in the array
np_2d.size

8

In [14]:
arr=np.array([[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [15]:
print(arr)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [16]:
arr.shape

(4, 3)

In [17]:
arr.size

12

In [18]:
arr.ndim

2

### some shortcuts:
#### shift +enter:to run and add one cell below
#### ctrl+enter:to run only
#### a/A:to add one cell above the cell
#### b/B:to add one cell below the cell
#### dd: press 2 times d to delete the cell
#### shift+tab:to know the syntax 

In [21]:
arr

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [22]:
type(arr)

numpy.ndarray

In [23]:
arr.dtype

dtype('int32')