In [1]:
import numpy as np

In [2]:
#array with only ones bydefault type is float
mat_1=np.ones(3)
print(mat_1)

[1. 1. 1.]


In [5]:
#to convert into int 
mat_1_int=np.ones(3,dtype=int)
print(mat_1_int)

[1 1 1]


In [6]:
mat_1_str=np.ones(3,dtype=str)
print(mat_1_str)

['1' '1' '1']


In [7]:
mat_1_bool=np.ones(3,dtype=bool)
print(mat_1_bool)

[ True  True  True]


In [8]:
mat_0=np.zeros((2,3),dtype=int)
print(mat_0)

[[0 0 0]
 [0 0 0]]


In [10]:
# empty matrix:bt it can hold some random values
mat_empty=np.empty((2,4),dtype=int)
print(mat_empty)

[[-1529812920         537     3801155     5570652]
 [    6619251     7536754     3014748     6881383]]


In [11]:
mat_r=np.empty((2,3),dtype=bool)
print(mat_r)

[[ True  True  True]
 [ True  True  True]]
