In [1]:
import numpy as np

In [2]:
l1=np.arange(2,8)
print(l1)

[2 3 4 5 6 7]


In [3]:
type(l1)

numpy.ndarray

In [4]:
l2=np.arange(2,8,2)
print(l2)

[2 4 6]


In [5]:
l2.dtype

dtype('int32')

In [6]:
l3=np.arange(5)
print(l3)

[0 1 2 3 4]


In [7]:
sp=np.linspace(1,10,5)
print(sp)

[ 1.    3.25  5.5   7.75 10.  ]


In [8]:
l4=np.arange(1,7)
print(l4)

[1 2 3 4 5 6]


In [9]:
#Reshape:convert into 2d array
reshape_mat=np.reshape(l4,(2,3))
print(reshape_mat)

[[1 2 3]
 [4 5 6]]


In [13]:
#3d array:(3d,2d,1d) i.e first is 3d column,then no of rows then no of columns
arr_3d=np.arange(1,13).reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
ar=np.arange(4,10).reshape(3,2)
print(ar)

[[4 5]
 [6 7]
 [8 9]]


In [12]:
#Ravel:convert 2d into 1d
ar2=np.ravel(ar)
print(ar2)

[4 5 6 7 8 9]


In [14]:
#flatten:it also convert into 1d arrray
flatten_mat=ar.flatten()
print(flatten_mat)

[4 5 6 7 8 9]


In [15]:
#transpose:it transpose the matrix
ar_transpose=ar.transpose()
print(ar_transpose)

[[4 6 8]
 [5 7 9]]
