In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,10).reshape(3,3)

In [3]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr2=np.arange(3,12).reshape(3,3)
print(arr2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
arr1+arr2

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [8]:
np.subtract(arr1,arr2)

array([[-2, -2, -2],
       [-2, -2, -2],
       [-2, -2, -2]])

In [10]:
np.add(arr1,arr2)

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [11]:
np.multiply(arr1,arr2)

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [12]:
np.divide(arr1,arr2)

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ],
       [0.77777778, 0.8       , 0.81818182]])

In [13]:
np.dot(arr1,arr2)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [14]:
arr1@arr2

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [15]:
np.max(arr1)

9

In [16]:
np.min(arr1)

1

In [17]:
np.mean(arr1)

5.0

In [18]:
np.std(arr1)

2.581988897471611

In [20]:
arr1.sum(axis=0)

array([12, 15, 18])

In [21]:
arr1.sum(axis=1)

array([ 6, 15, 24])

In [22]:
arr1.min(axis=1)

array([1, 4, 7])

In [23]:
np.min(arr1,axis=1)

array([1, 4, 7])

In [24]:
arr1.argmax()

8

In [25]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [26]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [29]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [32]:
np.exp(arr2)

array([[2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])