In [1]:
import numpy as np

In [2]:
ar1=np.arange(1,17).reshape(4,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
ar2=np.arange(17,33).reshape(4,4)
ar2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

## concatenate():

In [9]:
#concatenate take tuple as argument
np.concatenate((ar1,ar2))   

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [10]:
np.concatenate((ar1,ar2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

### hstack() and vstack()

In [12]:
np.hstack((ar1,ar2))         #hstack for adding horizontally

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [13]:
np.vstack((ar1,ar2))           #vstack for adding vertically

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [16]:
a=np.hstack((ar1,ar2,ar1))
a

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [17]:
a.shape

(4, 12)

## split():

In [18]:
array1d=np.array([2,3,4,5,6,7])
array1d

array([2, 3, 4, 5, 6, 7])

In [19]:
np.split(array1d,[3,6])

[array([2, 3, 4]), array([5, 6, 7]), array([], dtype=int32)]

In [20]:
np.split(array1d,[4,2])

[array([2, 3, 4, 5]), array([], dtype=int32), array([4, 5, 6, 7])]

In [21]:
np.split(array1d,[2,4,5])

[array([2, 3]), array([4, 5]), array([6]), array([7])]

In [23]:
np.split(a,3,axis=1)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]), array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])]