In [1]:
import numpy as np
import random

### random():value btw 0 &1

In [2]:
np.random.random(1)

array([0.14678168])

In [3]:
np.random.random(5)

array([0.02753662, 0.58515805, 0.13693241, 0.82472179, 0.67257353])

In [32]:
np.random.random((3,3))

array([[0.93096241, 0.10884769, 0.94723061],
       [0.82168998, 0.86505717, 0.16256521],
       [0.33320049, 0.47082123, 0.44334873]])

### randint():takes the range

In [4]:
np.random.randint(3)

1

In [6]:
np.random.randint(1,5,(3,3))

array([[1, 3, 2],
       [4, 3, 2],
       [1, 2, 2]])

In [33]:
np.random.randint(2,5,(2,3,4))

array([[[2, 3, 4, 2],
        [4, 3, 4, 3],
        [3, 3, 2, 4]],

       [[4, 3, 2, 3],
        [4, 2, 3, 3],
        [2, 4, 2, 4]]])

### rand(): give value btw 0 &1

In [7]:
np.random.rand(4)

array([0.75871264, 0.95516699, 0.57330127, 0.85309707])

In [11]:
np.random.rand(2,2)

array([[0.46851035, 0.0851541 ],
       [0.43531382, 0.17202011]])

### choice():give value by choice randomly

In [12]:
x=[2,3,4,5]
magic=np.random.choice(x)
magic

3

In [13]:
for i in range(10):
    print(np.random.choice(x))

3
4
4
2
4
2
2
3
4
4


### randn(): it gives negative value also bt range is 0&1

In [14]:
np.random.randn(4)

array([-0.3730093 ,  0.22878506, -1.2370062 , -0.36968332])

In [15]:
np.random.randn(2,3)

array([[ 1.56790263, -1.55616858,  0.92395082],
       [-0.21918106, -1.91792923, -0.3985753 ]])

In [17]:
np.random.randn(2,5)

array([[-0.70359902,  0.32155506, -1.57798345,  1.61160021, -2.22001805],
       [ 0.17481204,  0.45394686, -1.30532622,  0.12591098,  0.39727253]])

### permutation(): it gives the permutation of numbers

In [21]:
np.random.permutation(7)

array([1, 5, 0, 6, 3, 2, 4])

In [22]:
x=[1,2,3,4,5,6,7,8,9]
for i in range(5):
    print(np.random.permutation(x))

[9 1 7 8 5 4 2 3 6]
[3 7 6 9 1 8 2 4 5]
[1 3 9 6 8 4 5 7 2]
[2 7 8 9 3 4 1 6 5]
[6 2 7 5 9 8 3 4 1]
